source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PushServicesLibrary_Example' do
  pod 'PushServicesLibrary', :path => '/Users/devalios/Xcode/Xcode_Push_services_Könyvtárak/Github/PushServicesLibrary'

end
